USE [master]
GO
/****** Object:  Database [Clima]    Script Date: 16/04/2021 21:05:52 ******/
CREATE DATABASE [Clima]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Clima', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Clima.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Clima_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Clima_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Clima] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Clima].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Clima] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Clima] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Clima] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Clima] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Clima] SET ARITHABORT OFF 
GO
ALTER DATABASE [Clima] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Clima] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Clima] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Clima] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Clima] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Clima] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Clima] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Clima] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Clima] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Clima] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Clima] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Clima] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Clima] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Clima] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Clima] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Clima] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Clima] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Clima] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Clima] SET  MULTI_USER 
GO
ALTER DATABASE [Clima] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Clima] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Clima] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Clima] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Clima] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Clima] SET QUERY_STORE = OFF
GO
USE [Clima]
GO
/****** Object:  Table [dbo].[Ciudades]    Script Date: 16/04/2021 21:05:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ciudades](
	[id_ciudad] [int] IDENTITY(1,1) NOT NULL,
	[id_pais] [int] NOT NULL,
	[descripcion] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Ciudades] PRIMARY KEY CLUSTERED 
(
	[id_ciudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Paises]    Script Date: 16/04/2021 21:05:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Paises](
	[id_pais] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Paises] PRIMARY KEY CLUSTERED 
(
	[id_pais] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ciudades]  WITH CHECK ADD  CONSTRAINT [FK_Ciudades_Paises] FOREIGN KEY([id_pais])
REFERENCES [dbo].[Paises] ([id_pais])
GO
ALTER TABLE [dbo].[Ciudades] CHECK CONSTRAINT [FK_Ciudades_Paises]
GO
USE [master]
GO
ALTER DATABASE [Clima] SET  READ_WRITE 
GO
